### ISSUE TITLE
Search bar example on iOS 14.2 chops search text

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-native-component-library#133]
#### Describe the bug
Search field text chopped off running on iOS 14.2. 
- Android Pixel XL API 29 has no issues.

#### What is the expected behavior?
Search text field to display all lower hanging characters like [g, q,]
#### What are the steps to reproduce?
1. Run project
2. Click on search example from app bar nav section

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/100776447-902dc700-33d2-11eb-93d7-b3b49353506e.png)

**Comment by joebochill** [comment]
@jeffvg this seems to be fixed by #137. Can you confirm if you are still seeing this issue and if not, close this bug?

**Comment by joebochill** [comment]
@jeffvg

**Comment by daileytj** [comment]
@daileytj double check that this has been fixed

**Comment by daileytj** [comment]
Good to go!
![Screen Shot 2022-11-28 at 1 36 18 PM](https://user-images.githubusercontent.com/13989985/204354524-d0a2ffc5-b131-43fa-8934-2dd68203ff03.png)
