### ISSUE TITLE
Rename 'family' to something else.

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-native-component-library#181]
#### Describe the desired behavior
Perhaps we call family something else in this context, like `set` or `library`.

#### Describe the current behavior
When specifying an icon using the object syntax, we ask users to provide a `family` and a `name`. 

#### Is this request related to a current issue?
No

#### Additional Context

We use family elsewhere to talk about categories of icons within an icon set (e.g. the status family or agriculture family or devices family), which might be confusing.

**Comment by daileytj** [comment]
Look into what other libraries are doing (e.g., react-native-elements).

**Comment by daileytj** [comment]
Or do we want to update the icon metadata to use the name `category` or something else?

**Comment by joebochill** [comment]
Closing this since we launched the library with 'family'
