### ISSUE TITLE
Handle Extra Large Accessibility Sizes on iOS

### ISSUE THREAD

**Issue by dshiverware** [brightlayer-ui/react-native-component-library#224]
At a meeting between Eaton and our team this morning, the issue of accessibility scaling came up. In our current app, we are capping the text size once the large fonts reach the point of completely breaking the interface. We don't have this sort of control with the scaling of some of the PX Blue components (such as the drawer menu). This isn't a high-priority request by any means from us, but I was asked to make a feature request here to potentially handle these "extra large" accessibility font cases. Currently, the app components scale very well on all the regular iOS "Larger Text" sizes. It's just when the iOS "Large Accessibility Sizes" option is toggled to go into the extreme large text that things start to break down a bit.

<img width="300" alt="Screen Shot 2021-10-27 at 10 26 19 AM" src="https://user-images.githubusercontent.com/26386179/139107519-16d8212e-1541-4f12-9bbd-79a6306d776c.png">

**Comment by emclaug2** [comment]
@dshiverware Could you please be more specific about what kind of control you'd be looking for in regards to PX Blue components?

**Comment by joebochill** [comment]
We could do something like setting up a Context Provider where users can specify whether or not they want to components to respond to the system font size. Or they could set the maximum allowable font-scale...something like:

```
import { FontScaleProvider } from '@brightlayer-ui/react-components';
...
const App = () => (
    <ThemeProvider theme={...}>
        <FontScaleProvider maxFontScale={2}>
            <MainAppContents/>
        </FontScaleProvider>
    </ThemeProvider>
)

```
