### ISSUE TITLE
UserMenu "within a header" story should render in a single row

### ISSUE THREAD

**Issue by daileytj** [brightlayer-ui/react-native-component-library#234]
#### Describe the bug
UserMenu "within a header" story does not render properly. The AppBar breaks into two rows.

#### What is the expected behavior?
UserMenu "within a header" story should render in a single row

#### What are the steps to reproduce?
1. Go to storybook `UserMenu` "within a header" story
2. Observe the brokenness

#### Screenshots or links to minimum reproduction example
![Simulator Screen Shot - iPhone 12 - 2021-12-14 at 15 34 49](https://user-images.githubusercontent.com/13989985/146076808-c1931d4a-adf8-4236-b35f-81da1244dc38.png)

#### Environment

Built w/
@pxblue/react-native-components@6.0.0
iPhone 12 simulator
iOS 14.1

**Comment by joebochill** [comment]
I would say yes we should keep it until we have a suitable replacement. But we can down-prioritize any storybook-exclusive issues.

**Comment by jeffvg** [comment]
This is updated in release v 6.0.3
