### ISSUE TITLE
Storybook throws 404 status on open-sans font

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-native-component-library#240]
#### Describe the bug
Both dev/master having issues loading up open-sans
#### What is the expected behavior?
no 404 on open sans
#### What are the steps to reproduce?
1. Go to https://brightlayer-ui-components.github.io/react-native-dev/?path=/story/intro-overview--brightlayer-ui-react-native-components
2. Open dev tools
3. view errors

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/148768980-cb07ec1b-64c8-4221-948d-72033d9c0416.png)

**Comment by huayunh** [comment]
It is interesting that all the 404's are for `open-sans-latin`. The regular `open sans` fonts are loaded and rendered just fine.

**Comment by emclaug2** [comment]
React is working, reference the react storybook and how the font is imported there.

**Comment by emclaug2** [comment]
If we're going to rescaffold our component docs, we shouldn't spend time on this issue.
