### ISSUE TITLE
Add InfoListItemProps prop to the DrawerNavItems

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-native-component-library#255]
#### Describe the desired behavior
Users should be able to override any of the underlying InfoListItem props when they use a DrawerNavItem.

#### Describe the current behavior
These properties are not exposed.

#### Additional Context

Refer to the discussion here: https://github.com/brightlayer-ui/react-native-component-library/pull/251#issuecomment-1069380911

This has already been implemented in the React component library — use that as a reference: https://github.com/brightlayer-ui/react-component-library/blob/master/components/src/core/Drawer/DrawerNavItem.tsx#L81

**Comment by bkarambe** [comment]
This is a duplicate issue of https://github.com/brightlayer-ui/react-native-component-library/issues/252
