### ISSUE TITLE
Storybook still using @pxblue stuff

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-native-component-library#256]
## Describe the bug

from dev branch, 

https://github.com/brightlayer-ui/react-native-component-library/blob/4313bdb46580f9097e4d75f174507f3fe550a95b/demos/storybook/package.json#L18-L23

## What is the expected behavior?

What is pxblue?

**Comment by bkarambe** [comment]
Probably would not want to fix this until we know how the future component library looks like.

**Comment by emclaug2** [comment]
I'll close this issue along with the other storybook-related issues.
