### ISSUE TITLE
Request to add drop-down component in CollapsibleHeaderLayout

### ISSUE THREAD

**Issue by swati-eaton** [brightlayer-ui/react-native-component-library#282]
#### We have a requirement to add drop-down component in “CollapsibleHeaderLayout’ for react native. Please have a look at the attached UX design where in header we need to show drop down.  

Component : https://brightlayer-ui-components.github.io/react-native/?path=/info/components-documentation--collapsible-header-layout

#### Additional Context
<img width="242" alt="UX_Design" src="https://user-images.githubusercontent.com/109328318/181059072-d20b558b-e3cd-4ee0-83cb-b39988cee538.png">

**Comment by huayunh** [comment]
This is a large commitment. I have written a story on JIRA: BLUI-3567. This issue will be left open to help external teams track the progress

**Comment by daileytj** [comment]
Put together a code snippet showing how to do this via the title prop on the header that triggers a bottomsheet menu. Drop that code snippet here and close the issue.

**Comment by bkarambe** [comment]
@swati-eaton Here's the code snippet which will help :

**Component**

`import React from 'react';
import { SafeAreaView, ScrollView, View, I18nManager } from 'react-native';
import { StackNavigationProp } from '@react-navigation/stack';
import RNRestart from 'react-native-restart';
import {
    ChannelValue,
    EmptyState,
    Header,
    Hero,
    HeroBanner,
    IconFamily,
    InfoListItem,
    ListItemTag,
    ScoreCard,
} from '@brightlayer-ui/react-native-components';
import { ThemedButton } from '@brightlayer-ui/react-native-components/themed';
import { Card, useTheme } from 'react-native-paper';

import MatIcon from 'react-native-vector-icons/MaterialIcons';
import * as BLUIColors from '@brightlayer-ui/colors';

import { RootStackParamList } from './router';
import { MobileStepperExample } from './components/mobile-stepper-example';
import { useThemeContext } from './contexts/ThemeContext';
import { UserMenuExample } from './components/user-menu-example';
import { KitchenSink } from './components/kitchen-sink';

const backgroundImage = require('./assets/images/farm.jpg');

const Sunny: IconFamily = { family: 'material', name: 'wb-sunny', direction: 'ltr' };
const Notifications: IconFamily = { family: 'material', name: 'notifications', direction: 'ltr' };
const Info: IconFamily = { family: 'material', name: 'info', direction: 'ltr' };
const Clouds: IconFamily = { family: 'material', name: 'cloud', direction: 'ltr' };
const ChartLineVariant: IconFamily = { family: 'material-community', name: 'chart-line-variant', direction: 'ltr' };
const Battery: IconFamily = { family: 'brightlayer-ui', name: 'battery', direction: 'auto' };
const A: IconFamily = { family: 'brightlayer-ui', name: 'grade_a', direction: 'ltr' };
const Temp: IconFamily = { family: 'brightlayer-ui', name: 'temp', direction: 'ltr' };
const Humidity: IconFamily = { family: 'brightlayer-ui', name: 'moisture', direction: 'ltr' };
const Pie: IconFamily = { family: 'material-community', name: 'chart-pie', direction: 'ltr' };
const Clock: IconFamily = { family: 'material-community', name: 'clock-outline', direction: 'ltr' };
const MailIcon: IconFamily = { family: 'material', name: 'mail', direction: 'ltr' };
const MenuIcon: IconFamily = { family: 'material', name: 'menu', direction: 'auto' };
const MoreIcon: IconFamily = { family: 'material', name: 'more-vert', direction: 'ltr' };

const PADDING = 10;

export const toggleRTL = (): void => {
    if (I18nManager.isRTL) {
        I18nManager.allowRTL(false);
        I18nManager.forceRTL(false);
    } else {
        I18nManager.forceRTL(true);
    }
    RNRestart.Restart();
};

type AppProps = {
    navigation: StackNavigationProp<RootStackParamList, 'App'>;
};

export const App: React.FC<AppProps> = ({ navigation }) => {
    const theme = useTheme();
    const { theme: themeType, setTheme } = useThemeContext();

    return (
        <View style={{ flex: 1, backgroundColor: theme.colors.background }}>
            <Header
                expandable={true}
                title={'South Tin Mill'}
                subtitle={'Gary Steel Works'}
                info={'Online'}
                icon={MenuIcon}
                onIconPress={(): void => {
                    navigation.openDrawer();
                }}
                actionItems={[
                    {
                        component: (
                            <UserMenuExample
                                onToggleRTL={toggleRTL}
                                onToggleTheme={(): void => setTheme(themeType === 'light' ? 'dark' : 'light')}
                            />
                        ),
                    },
                ]}
                backgroundImage={backgroundImage}
                searchableConfig={{ placeholder: 'Search', autoFocus: true }}
            />
            <ScrollView>
                <Card style={{ padding: 0, margin: PADDING, marginBottom: 0 }}>
                    <EmptyState
                        title={'Nothing Found'}
                        description={'Not a single thing'}
                        icon={ChartLineVariant}
                        actions={
                            <ThemedButton mode={'outlined'} icon={'plus'}>
                                Add a Device
                            </ThemedButton>
                        }
                    />
                </Card>
                <Card style={{ padding: 0, margin: PADDING, marginBottom: PADDING }}>
                    <HeroBanner>
                        <Hero
                            label={'Healthy'}
                            value={96}
                            units={'/100'}
                            icon={A}
                            fontSize={20}
                            iconColor={theme.dark ? BLUIColors.green[200] : BLUIColors.green[500]}
                        />
                        <Hero
                            label={'Battery'}
                            value={'Full'}
                            icon={Battery}
                            iconColor={theme.dark ? BLUIColors.blue[200] : BLUIColors.blue[500]}
                        />
                        <Hero label={'Estimated'} icon={Clock} iconColor={BLUIColors.gray[500]}>
                            <ChannelValue fontSize={20} value={1} units={'h'} />
                            <ChannelValue fontSize={20} value={37} units={'m'} />
                        </Hero>
                        <Hero
                            label={'Loaded'}
                            icon={Pie}
                            iconColor={theme.dark ? BLUIColors.blue[200] : BLUIColors.blue[500]}
                        >
                            <ChannelValue fontSize={20} value={65} units={'%'} icon={ChartLineVariant} />
                        </Hero>
                        <Hero
                            label={'Not Shown'}
                            value={'5th Item'}
                            icon={Battery}
                            iconColor={theme.dark ? BLUIColors.blue[200] : BLUIColors.blue[500]}
                        />
                    </HeroBanner>
                    <InfoListItem
                        divider={'full'}
                        icon={Sunny}
                        title={'Temperature'}
                        rightComponent={<ChannelValue value={68} units={'°F'} />}
                    />
                    <InfoListItem
                        divider={'full'}
                        icon={Sunny}
                        title={'Temperature'}
                        rightComponent={<ChannelValue value={68} units={'°F'} />}
                    />
                    <InfoListItem
                        divider={'full'}
                        icon={Sunny}
                        title={'Temperature'}
                        rightComponent={
                            <React.Fragment>
                                <ChannelValue value={1} units={'h'} icon={Clock} />
                                <ChannelValue value={24} units={'m'} />
                            </React.Fragment>
                        }
                    />
                </Card>
                <InfoListItem
                    title={'Emerson Field West'}
                    subtitle={['DG 100', 'EDR 5000', 'Online']}
                    statusColor={BLUIColors.green[500]}
                    hidePadding={true}
                    icon={Battery}
                    avatar
                    rightComponent={<MatIcon name={'mail'} size={24} color={theme.colors.text} />}
                    divider={'partial'}
                    onPress={(): void => {
                        /* do nothing */
                    }}
                />
                <InfoListItem
                    title={'South Hills Farm'}
                    subtitle={'Offline'}
                    statusColor={BLUIColors.red[500]}
                    divider={'full'}
                    icon={Pie}
                    iconAlign={'center'}
                    hidePadding={false}
                    fontColor={theme.dark ? BLUIColors.red[200] : BLUIColors.red[500]}
                    rightComponent={<ChannelValue value={15} units={'A'} color={theme.colors.text} />}
                    onPress={(): void => {
                        /* do nothing */
                    }}
                />
                <InfoListItem
                    title={'Cherry East'}
                    subtitle={['DG 100', 'EDR 5000', 'Online']}
                    subtitleSeparator={'/'}
                    hidePadding
                    rightComponent={<ListItemTag label={'ACTIVE'} />}
                    onPress={(): void => {
                        /* do nothing */
                    }}
                />
                <ScoreCard
                    style={{ margin: PADDING }}
                    headerTitle={'Portland Datacenter Long Name'}
                    headerSubtitle={'6 UPS Devices'}
                    headerInfo={'Attention Required'}
                    headerBackgroundImage={backgroundImage}
                    headerColor={BLUIColors.blue[500]}
                    actionItems={[
                        {
                            icon: MoreIcon,
                            onPress: (): void => {
                                /* do nothing */
                            },
                        },
                    ]}
                    badgeOffset={-55}
                    badge={
                        <HeroBanner style={{ flex: 0, minWidth: 80, justifyContent: 'flex-end' }}>
                            <Hero
                                label={'Score'}
                                iconSize={48}
                                iconColor={theme.dark ? BLUIColors.green[200] : BLUIColors.green[500]}
                                value={98}
                                units={'/100'}
                                icon={A}
                            />
                        </HeroBanner>
                    }
                    actionRow={
                        <InfoListItem
                            dense
                            chevron
                            hidePadding
                            title={'View Location'}
                            onPress={(): void => {
                                /* do nothing */
                            }}
                        />
                    }
                >
                    <View style={{ justifyContent: 'center', marginLeft: -16 }}>
                        <InfoListItem
                            dense
                            icon={Notifications}
                            iconColor={BLUIColors.red[500]}
                            title={'1 Alarm'}
                            fontColor={theme.dark ? BLUIColors.red[200] : BLUIColors.red[500]}
                        />
                        <InfoListItem
                            dense
                            icon={Info}
                            iconColor={theme.dark ? BLUIColors.blue[200] : BLUIColors.blue[500]}
                            title={'1 Event'}
                        />
                        <InfoListItem dense icon={Clouds} title={'Online'} />
                    </View>
                </ScoreCard>
                <ScoreCard
                    style={{ margin: PADDING, marginTop: 0 }}
                    headerColor={BLUIColors.red[500]}
                    headerTitle={'Substation 3'}
                    headerSubtitle={'High Humidity Alarm'}
                    headerInfo={'5 Devices'}
                    headerBackgroundImage={backgroundImage}
                    actionItems={[
                        {
                            icon: MailIcon,
                            onPress: (): void => {
                                /* do nothing */
                            },
                        },
                        {
                            icon: MoreIcon,
                            onPress: (): void => {
                                /* do nothing */
                            },
                        },
                    ]}
                    badge={
                        <HeroBanner style={{ flex: 0, minWidth: 180, justifyContent: 'flex-end' }}>
                            <Hero label={'Temperature'} iconSize={70} value={69} units={'°F'} icon={Temp} />
                            <Hero
                                label={'Humidity'}
                                iconSize={70}
                                iconColor={BLUIColors.blue[200]}
                                value={78}
                                units={'%'}
                                icon={Humidity}
                            />
                        </HeroBanner>
                    }
                    actionRow={
                        <InfoListItem
                            dense
                            chevron
                            hidePadding
                            title={'View Location'}
                            onPress={(): void => {
                                /* do nothing */
                            }}
                        />
                    }
                >
                    <View style={{ justifyContent: 'center', marginLeft: -16 }}>
                        <InfoListItem
                            dense
                            icon={Notifications}
                            iconColor={BLUIColors.red[500]}
                            title={'1 Alarm'}
                            fontColor={theme.dark ? BLUIColors.red[200] : BLUIColors.red[500]}
                        />
                        <InfoListItem
                            dense
                            icon={Info}
                            iconColor={theme.dark ? BLUIColors.blue[200] : BLUIColors.blue[500]}
                            title={'1 Event'}
                        />
                        <InfoListItem dense icon={Clouds} title={'Online'} />
                    </View>
                </ScoreCard>

                <MobileStepperExample />

                <KitchenSink />

                <SafeAreaView />
            </ScrollView>
        </View>
    );
};`

//Bottom Sheet

`import React, { ReactNode } from 'react';
import { SafeAreaView, StyleSheet, ViewStyle } from 'react-native';
import Modal from 'react-native-modal';
import { useTheme } from 'react-native-paper';

type BottomSheetProps = {
    children?: ReactNode;
    show?: boolean;
    onClose?: () => void;
    backgroundColor?: string;
    styles?: {
        root?: ViewStyle;
        background?: ViewStyle;
    };
};

const useStyles = (
    theme: ReactNativePaper.Theme,
    props: BottomSheetProps
): StyleSheet.NamedStyles<{
    root: ViewStyle;
    background: ViewStyle;
}> =>
    StyleSheet.create({
        root: {
            justifyContent: 'flex-end',
            margin: 0,
        },
        background: {
            backgroundColor: props.backgroundColor || theme.colors.surface,
        },
    });

export const BottomSheet: React.FC<BottomSheetProps> = (props) => {
    const { show, children, onClose, styles = {} } = props;
    const theme = useTheme();
    const defaultStyles = useStyles(theme, props);

    return (
        <Modal
            isVisible={show}
            backdropOpacity={0.5}
            onBackdropPress={onClose}
            supportedOrientations={['portrait', 'landscape']}
            style={[defaultStyles.root, styles.root]}
        >
            <SafeAreaView style={[defaultStyles.background, styles.background]}>{children}</SafeAreaView>
        </Modal>
    );
};
`

**Comment by joebochill** [comment]
We are not planning to build a dedicated component for this (we don't recommend using dropdown menus on mobile — we prefer the bottom sheet approach shown above), but the code snippet above should give you an idea for how you can implement this with a TouchableOpacity and a Modal.

**Comment by swati-eaton** [comment]
We will try it out. Thanks.
