### ISSUE TITLE
Navigation tabs inside CollapsibleHeaderLayout are not supported

### ISSUE THREAD

**Issue by swati-eaton** [brightlayer-ui/react-native-component-library#288]
####  We need to add Tab.Navigator inside CollapsibleHeaderLayout 
Component : https://brightlayer-ui-components.github.io/react-native/?path=/info/components-documentation--collapsible-header-layout

#### When we try to do same, corresponding tabs screens are not getting rendered and swipe functionality is also not working.
 
```
<CollapsibleHeaderLayout
                HeaderProps={{
                    variant: 'dynamic',
                    title: 'School of fine arts',
                    subtitle: 'Org name',
                    info: 'location',
                    icon: { name: 'arrow-back' },
                    onIconPress: () => {
                        navigation.pop();
                    },
                    actionItems: [{ icon: { name: 'edit' }, onPress: () => {} }],
                    collapsedHeight: 50,
                    expandedHeight: 200,
                    expandable: true,
                }}
                               
                <Tab.Navigator
                    screenOptions={{
                        swipeEnabled: true,
                    }}
                >
                    <Tab.Screen name="Help" component={Help} />
                    <Tab.Screen name="AccountSettings" component={AccountSettings} />
                </Tab.Navigator>
            >
</CollapsibleHeaderLayout>
```

<img width="190" alt="UX_Design" src="https://user-images.githubusercontent.com/109328318/182909830-5d61f233-f8d4-4d30-bf33-45151163dca4.png">

**Comment by daileytj** [comment]
From Swati Jain:

"I have tried by keeping tab navigator outside of the CollapsibleHeader component and with this we are able to render the tabs perfectly But header is not scrollable with this approach as it will not have much content to get scroll area. 

As per current UX design, it’s expected to scroll (expand/collapse) header and to achieve this all the bottom content we should keep it inside CollapsibleHeader. "

**Comment by daileytj** [comment]
See if we can put together a code snippet for this.

**Comment by swati-eaton** [comment]
Hi @daileytj Did you get a chance to look into this ?

**Comment by bkarambe** [comment]
> <CollapsibleHeaderLayout
>                 HeaderProps={{
>                     variant: 'dynamic',
>                     title: 'School of fine arts',
>                     subtitle: 'Org name',
>                     info: 'location',
>                     icon: { name: 'arrow-back' },
>                     onIconPress: () => {
>                         navigation.pop();
>                     },
>                     actionItems: [{ icon: { name: 'edit' }, onPress: () => {} }],
>                     collapsedHeight: 50,
>                     expandedHeight: 200,
>                     expandable: true,
>                 }}
>                                
>                 <Tab.Navigator
>                     screenOptions={{
>                         swipeEnabled: true,
>                     }}
>                 >
>                     <Tab.Screen name="Help" component={Help} />
>                     <Tab.Screen name="AccountSettings" component={AccountSettings} />
>                 </Tab.Navigator>
>             >
> </CollapsibleHeaderLayout>



> Hi @daileytj Did you get a chance to look into this ?

Hi @swati-eaton We are currently looking at this issue. We will update you soon.
