### ISSUE TITLE
Showcase empty state icon not always loading on android device

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-native-component-library#80]
#### Describe the bug
The empty state component icon (Chart Line Variants) not loading up on android

#### What is the expected behavior?
icon to display

#### What are the steps to reproduce?
1. Run yarn start:showcase-android
2. Empty state icon not loading

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/90399479-00ede500-e069-11ea-8f0a-0c097c21609a.png)

#### Environment

Windows
Android

**Comment by joebochill** [comment]
I haven't seen this in a while...can we look and see if it's still reproducible?

**Comment by daileytj** [comment]
Closing this issue as it is rendering fine on android now.
![Screen Shot 2022-07-13 at 9 39 59 AM](https://user-images.githubusercontent.com/13989985/178747572-b5d6bf1f-c5ae-4991-a578-bb171373c9d8.png)
